### PR TITLE
Restrict profile validation to submitted data only

### LINKED ISSUE #277: Incorrect validation result for a JSON profile
Profiles defined by JSON are not validating correctly - the wrong number of errors is being reported.  An example output is below.  15 errors are being reported, but there are only 9 fields, all of which are mandatory.  In this example, the number of errors should be 7, because there are 7 fields with no values.

```json
{
    "total": 15,
    "errors": [
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "This field cannot be empty",
            "fieldName": "Type",
            "metadataPropertyName": "type"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "This field cannot be empty",
            "fieldName": "Reference",
            "metadataPropertyName": "reference"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "This field cannot be empty",
            "fieldName": "Subject",
            "metadataPropertyName": "subject"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "This field cannot be empty",
            "fieldName": "Effective Date",
            "metadataPropertyName": "effectiveDate"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "This field cannot be empty",
            "fieldName": "Reason for Change",
            "metadataPropertyName": "reasonForChange"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        },
        {
            "message": "This field cannot be empty",
            "fieldName": "Sponsor",
            "metadataPropertyName": "sponsor"
        },
        {
            "message": "Property [description] of class [class uk.ac.ox.softeng.maurodatamapper.profile.domain.ProfileField] cannot be blank"
        }
    ],
    "fieldTotal": 7
}
```

### PR DESCRIPTION
**Pull request by joe-crawford**
- Don't validate profile structure as part of profile `/validate` endpoint (resolves #277)

### CODE REVIEW

**Comment by joe-crawford** [comment]
See issue #286 for future enhancements to validate profile definitions as well as submitted profile field values.

**Comment by joe-crawford** [comment]
First PR build failed, but I think it must have been due to a timing issue. Rerunning the build passed.

**Comment by joe-crawford** [comment]
Failing test is in a different area. It also looks like it could be a timing issue.

**Review by olliefreeman — CHANGES_REQUESTED** [review]
As we're going to ultimately want to validate a profile as a separate piece of work can we improve this now so we're ready when we want to provide this functionality. 

As we're messing with the concept of validation, and what changes you've made are correct but you've changed the meaning of "validate" on the profile POJO.

I would suggest  we introduce an addtl service method "validateProfileContent" or something, which calls cleanProfile.validateContent, and then performs the validate checking the current value only, this way we maintain the original validate concept which is to check the validity of a profile as an object, and add the concept of checking the validity of the profile's values/content ... im not sold on the naming of "validateProfileContent" as its not clear what its validating.

You can then add/adapt the validate methods to perform both functions in whatever manner you see fit.

**Comment by joe-crawford** [comment]
> As we're going to ultimately want to validate a profile as a separate piece of work can we improve this now so we're ready when we want to provide this functionality.
> 
> As we're messing with the concept of validation, and what changes you've made are correct but you've changed the meaning of "validate" on the profile POJO.
> 
> I would suggest we introduce an addtl service method "validateProfileContent" or something, which calls cleanProfile.validateContent, and then performs the validate checking the current value only, this way we maintain the original validate concept which is to check the validity of a profile as an object, and add the concept of checking the validity of the profile's values/content ... im not sold on the naming of "validateProfileContent" as its not clear what its validating.
> 
> You can then add/adapt the validate methods to perform both functions in whatever manner you see fit.

Change to restore original `validate` behaviour is in PR #293 (custom validation flag is added to validate `params` map object), and a `validateCurrentValues` service method has been added.

**Comment by joe-crawford** [comment]
Closing this PR as it has been superseded by PR #293.

**Pull request closed without merging**
