### PR TITLE
gh-475 Edit history for merged items under versioned folders

### LINKED ISSUE #475: Record the merging of a versioned folder into the individual target items
# Description

When a versioned folder is merged into a target versioned folder, currently an overall commit message is recorded on the target VF to represent the change history.

This should be extended to add a history record to each individual item that was changed in the target VF too. This will highlight at a more granular level how the merge affected the VF.

# Merge operation

The `VersionedFolderService.mergeObjectPatchDataIntoVersionedFolder()` method has three top level operations to take care of for every patched item/field change:

- Created items in the target
- Deleted items from the target
- Modified items in the target

For each one, a new history record should be added as each catalogue item is changed/created using the `EditHistoryAware` trait. The `EditTitle.MERGE` enum should be used along with a suitable description referencing the source versioned folder that caused the change, e.g.

- "Item created in branch 'my-test-branch'"
- "Item modified in branch 'my-test-branch'"
- etc

# Created and updated items

As items are created (copied) or modified in the target versioned folder, the history should be added directly to that new/updated item in question.

# Deleted items

Where items have been deleted from the target versioned folder, the history item should be added to the parent item that used to own the child deleted item.

### PR DESCRIPTION
**Pull request by pjmonks**
Resolves #475 

Track at an item level changes that have happened to items under a versioned folder during a merge:

- Created/modified items have a `MERGE` edit history record attached to them.
- Deleted items have a `MERGE` edit history record attached to their parent (or the target versioned folder if not available).

This then results in a visible change history at the item level, as well as the `CHANGELOG` entry recorded on the versioned folder itself.

image

I have adjusted the `mdm-testing-functional` tests for Versioned Folder merging to carry out some spot checks to ensure that these `MERGE` history entries are at least being recorded.

### CODE REVIEW

**Comment by pjmonks** [comment]
I have pushed some fixes due to failed tests, part of my changes broke parameter lists and overridden methods in the `ModelService`. All the merge tests pass now, but one new test has failed for `ProfileFunctionalSpec` in `mdm-testing-functional`. This originally passed before and passes locally on my machine, I'm hoping this is an outlier.

**Comment by jamesrwelch** [comment]
The code changes look good and the tests look sensible.  I've just tried it myself, on a minimal versioned folder, and I'm not getting any `MERGE` edits for the PrimitiveType that I've modified.  Have I done something wrong?

**Comment by pjmonks** [comment]
@jamesrwelch I've found the cause of your issue, the data type is recording the edit history during the merge correctly, as you can see in Postgres:

image

The problem is actually the UI, it's requesting a resource type of `dataTypes` but needs to be more specific like `primitiveTypes`, so it is not fetching the history correctly.

Here are the current known issues related to merging and the change history:

- #479 
- MauroDataMapper/mdm-ui#889
- MauroDataMapper/mdm-ui#890

**Review by jamesrwelch — APPROVED** [review]
I've had a play and it seems to work nicely - the code changes look good too.  Well done for making this fairly major change so quickly!  
I agree the failing test in Jenkins is unrelated
With the caveat that the other issues reported will also need fixing, I'm very happy with this 👍

**Pull request merged**
