### PR TITLE
Optimise the deletion of versioned folders by reducing the number of queries

### PR DESCRIPTION
**Pull request by jamesrwelch**
This PR massively speeds up the deletion of Versioned Folders by reducing the number of queries and not building the breadcrumb tree white so often

### CODE REVIEW

**Comment by jamesrwelch** [comment]
This also includes a change to fix #355 - sorry, was going to include that in a separate PR but it's quite related.

**Comment by joe-crawford** [comment]
Hi @jamesrwelch, there's a number of failing tests on this branch that look like they may be related? E.g. tests under `ModelUserAccessPermissionChangingAndVersioningFunctionalSpec` which also are failing locally for me, I think these may need double checking if they're OK or not?

**Comment by jamesrwelch** [comment]
All tests are now passing.  But something odd has happened to my local instance and I want to check it's not related - so please don't merge this one quite yet!

**Comment by jamesrwelch** [comment]
Ok, it's my mistake - I hadn't rebased on top of develop.  This one's good to go.

**Comment by jamesrwelch** [comment]
(Note the force-push)

**Review by pjmonks — APPROVED** [review]
I think this change looks good. From my understanding you're avoiding the final flush and security rebuild until the end when the top level folder is finally removed.

I've tested this before on my local instance and can definitely see the speed improvement, plus it works as I expect. I approve this.

**Comment by jamesrwelch** [comment]
> From my understanding you're avoiding the final flush and security rebuild until the end when the top level folder is finally removed.

Yes - doing it after removing each model and folder in the Versioned Folder was unnecessarily slow

**Pull request merged**
