### PR TITLE
gh-245 Restrict ability to create folders and classifiers

### PR DESCRIPTION
**Pull request by GBishop-PHSA**
gh-245 Created configuration to limit ability of non-admin users to create root folders or move exisiting folders to the root. 
Created configuration to limit ability of non-admin users to create classifiers

Configuration 
category:  security
key: security.restrict.root.folder

category: security
key: security.restrict.classifier.create

### CODE REVIEW

**Comment by GBishop-PHSA** [comment]
@joe-crawford I added a new endpoint as part of this ticket, but the test in BaseUrlMappingsReportSpec fails because the url is not documented at https://documenter.getpostman.com/.

Is this something I need to do as part of the pull request?

**Comment by joe-crawford** [comment]
Hi @GBishop-PHSA,

Ah yes, there's an automated check that endpoints are in the Postman collection (https://documenter.getpostman.com/view/9840589/UVC8BkkA) in the tests.

To add the new/edited endpoints to the tests, please can you:

* Import the Postman collection and environment from https://github.com/MauroDataMapper/postman-library to your local Postman
* Edit the appropriate endpoints
* Make a new collection called Updates, transfer the updated endpoints to the new collection
* Export the Updates collection and upload here or send to us
* We'll merge it into the main Postman collection

(We're limited on the number of members of the main collection so can't add more than 3 Postman contributors directly.)

**Comment by GBishop-PHSA** [comment]
@joe-crawford Yes, this is ready for review

**Review by joe-crawford — APPROVED** [review]
Looks good and have successfully tested locally. Thanks @GBishop-PHSA!

**Pull request merged**
